import type { PlayerSettings, PresetId, SettingsKey } from "./types";

export const DEFAULT_SETTINGS: PlayerSettings = {
  chinese: true,
  pinyin: true,
  english: true,
  grammar: true,
  vocab: true,
  idiom: true,
  notes: true,
  beijing: true,
  culture: true,
  decks: true,
  drills: true,
  registerRewrite: true,
  speaker: true,
  timestamp: true,
  sceneImage: true,
  breakdown: true,
  audioChinese: true,
  audioEnglish: false,
  audioPinyin: false,
  audioNarrator: true,
};

export const SETTING_LABELS: Record<SettingsKey, string> = {
  chinese: "中文 Chinese text",
  pinyin: "拼音 Pinyin text",
  english: "English text",
  grammar: "Pause for grammar cards",
  vocab: "Pause for vocabulary cards",
  idiom: "Pause for idiom cards 成语",
  notes: "Pause for teaching notes",
  beijing: "Pause for 北京话 Beijing speech",
  culture: "Pause for culture notes",
  decks: "Pause for vocabulary review decks",
  drills: "Show practice drills on cards",
  registerRewrite: "Textbook rewrite of colloquial lines",
  speaker: "Speaker names",
  timestamp: "Timestamps",
  sceneImage: "Scene illustration",
  breakdown: "Character breakdown",
  audioChinese: "🔊 Chinese audio",
  audioEnglish: "🔊 English audio",
  audioPinyin: "🔊 Slow Chinese (pinyin pace)",
  audioNarrator: "🔊 Narrator explains cards",
};

export const PRESETS: Record<PresetId, PlayerSettings> = {
  full: { ...DEFAULT_SETTINGS },
  immersion: {
    ...DEFAULT_SETTINGS,
    english: false,
    pinyin: false,
    grammar: false,
    vocab: false,
    idiom: false,
    notes: false,
    beijing: false,
    culture: false,
    decks: false,
    drills: false,
    registerRewrite: false,
    breakdown: false,
    audioChinese: true,
    audioEnglish: false,
    audioPinyin: false,
    audioNarrator: false,
  },
  reading: {
    ...DEFAULT_SETTINGS,
    english: false,
    grammar: false,
    vocab: false,
    idiom: false,
    notes: false,
    beijing: true,
    culture: false,
    decks: false,
    drills: false,
    registerRewrite: true,
    breakdown: false,
    audioChinese: true,
    audioEnglish: false,
    audioPinyin: true,
    audioNarrator: true,
  },
  minimal: {
    ...DEFAULT_SETTINGS,
    english: false,
    pinyin: false,
    grammar: false,
    vocab: false,
    idiom: false,
    notes: false,
    beijing: false,
    culture: false,
    decks: false,
    drills: false,
    registerRewrite: false,
    breakdown: false,
    speaker: false,
    timestamp: false,
    audioChinese: true,
    audioEnglish: false,
    audioPinyin: false,
    audioNarrator: false,
  },
};

export const PRESET_BUTTONS: { id: PresetId; label: string }[] = [
  { id: "immersion", label: "Uninterrupted story" },
  { id: "full", label: "All teaching pauses" },
  { id: "reading", label: "Reading" },
  { id: "minimal", label: "Chinese only" },
];

export const SETTING_GROUPS: { label: string; keys: SettingsKey[] }[] = [
  {
    label: "Story interruptions — off = skip",
    keys: [
      "grammar",
      "idiom",
      "vocab",
      "decks",
      "notes",
      "beijing",
      "culture",
      "drills",
    ],
  },
  {
    label: "Subtitles",
    keys: [
      "chinese",
      "pinyin",
      "english",
      "speaker",
      "timestamp",
      "registerRewrite",
      "breakdown",
    ],
  },
  {
    label: "Audio",
    keys: ["audioChinese", "audioPinyin", "audioEnglish", "audioNarrator"],
  },
];
